### ISSUE TITLE
Missing files in the examples

### ISSUE THREAD

**Issue by rave78** [mvsjober/hypercluster#1]
[myprog_train.py](https://github.com/CSCfi/slurm-hyper-search/blob/d7ec7a133596f09ec8c49e5632096d547fe9f568/run-example.sh#L35) and [myprog_eval.py](https://github.com/CSCfi/slurm-hyper-search/blob/d7ec7a133596f09ec8c49e5632096d547fe9f568/run-example.sh#L45) in [run-example.sh](https://github.com/CSCfi/slurm-hyper-search/blob/master/run-example.sh#L45) are missing.  Could you please upload the missing files?

**Comment by mvsjober** [comment]
Those are not actual files but meant to be place-holders for you own files. As it is said in the the README.md:

> First, you need to edit the [run-example.sh](https://github.com/CSCfi/slurm-hyper-search/blob/master/run-example.sh) script for your particular case. Typically it will run a training script with the given parameters, and then evaluate the results producing some evaluation measures.
